addIngredient("dinosaur_meat",{
    type:"meat",
    color:"#4C121B",
    shape:"ear",
    group:"meat",
    scale:2.0,
    keywords:"primitive,dino,old,meat",
    dishName:"dino_meat",
    cookColor:"#3E1E1B",
    adj:"dino_meat",
    broken:"minced_dino_meat"
  });

addIngredient("minced_dino_meat",{
    group:"meat",
    color:"#4C121B",
    shape:"noodles",
    scale:1.5,
    dishName:"minced_dino_meat",
    cookColor:"#3E1E1B",
    hidden:true,
    adj:"ground_dino_meat",
    broken:"minced_dino_meat"
  });

addIngredient("chuck",{
    type:"beef",
    shape:"rectangle_round_rough",
    group:"generic",
    scale:1.0,
    keywords:"beef,cow,meat,steak",
    dishName:"beef_chuck",
    adj:"chuck"
  });

addIngredient("brisket",{
    type:"beef",
    shape:"cutlet",
    color:"#9A2020",
    group:"generic",
    scale:1.0,
    keywords:"beef,cow,meat,steak",
    dishName:"briskets",
    adj:"brisket"
  });
